version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days-before-reopen: 5
      semver-major-days-before-reopen: 30
