name: Deploy Balance Production

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: gunk-dev/armstrong/.github/workflows/deploy-fly.yml@a6d7477603edc714512ac3cb1e786f4f059e2c9c # main
    with:
      app-name: balance-prod
      cue-path: ./apps/balance
      environment: prod
      nix-target: balance-oci-image
      image-name: balance
      health-check-path: /api/health
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
