name: Deploy Flux Preview

on:
  repository_dispatch:
    types: [flux-preview, flux-preview-cleanup]

permissions: {}

jobs:
  preview:
    if: github.event.action == 'flux-preview'
    uses: gunk-dev/armstrong/.github/workflows/preview-fly.yml@a6d7477603edc714512ac3cb1e786f4f059e2c9c # main
    with:
      app-prefix: flux-preview
      cue-path: ./apps/flux
      nix-target: oci-image
      nix-input-name: flux
      image-name: flux
      source-repo: gunk-dev/flux
      pr-number: ${{ github.event.client_payload.pr_number }}
      head-sha: ${{ github.event.client_payload.head_sha }}
      action: deploy
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

  cleanup:
    if: github.event.action == 'flux-preview-cleanup'
    uses: gunk-dev/armstrong/.github/workflows/preview-fly.yml@a6d7477603edc714512ac3cb1e786f4f059e2c9c # main
    with:
      app-prefix: flux-preview
      cue-path: ./apps/flux
      nix-target: oci-image
      nix-input-name: flux
      image-name: flux
      source-repo: gunk-dev/flux
      pr-number: ${{ github.event.client_payload.pr_number }}
      action: cleanup
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
