name: Deploy Flux Production

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: gunk-dev/armstrong/.github/workflows/deploy-fly.yml@main
    with:
      app-name: flux-prod
      cue-path: ./apps/flux
      environment: prod
      nix-target: oci-image
      image-name: flux
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
