name: Deploy Flux Staging

on:
  push:
    branches: [main]
    paths:
      - 'flake.lock'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: gunk-dev/armstrong/.github/workflows/deploy-fly.yml@a6d7477603edc714512ac3cb1e786f4f059e2c9c # main
    with:
      app-name: flux-staging
      cue-path: ./apps/flux
      environment: staging
      nix-target: oci-image
      image-name: flux
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
