name: Deploy Web Production

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: gunk-dev/armstrong/.github/workflows/deploy-fly.yml@a6d7477603edc714512ac3cb1e786f4f059e2c9c # main
    with:
      app-name: gunk-web-prod
      cue-path: ./apps/web
      environment: prod
      nix-target: web-oci-image
      image-name: gunk-web
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
