name: Deploy Web Preview

on:
  repository_dispatch:
    types: [web-preview, web-preview-cleanup]

permissions: {}

jobs:
  preview:
    if: github.event.action == 'web-preview'
    uses: gunk-dev/armstrong/.github/workflows/preview-fly.yml@b27877e3fcbddb494a9f675aab36785c26138736 # main
    with:
      app-prefix: gunk-web-preview
      cue-path: ./apps/web
      nix-target: web-oci-image
      nix-input-name: gunk-web
      image-name: gunk-web
      source-repo: gunk-dev/gunk-web
      pr-number: ${{ github.event.client_payload.pr_number }}
      head-sha: ${{ github.event.client_payload.head_sha }}
      action: deploy
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

  cleanup:
    if: github.event.action == 'web-preview-cleanup'
    uses: gunk-dev/armstrong/.github/workflows/preview-fly.yml@b27877e3fcbddb494a9f675aab36785c26138736 # main
    with:
      app-prefix: gunk-web-preview
      cue-path: ./apps/web
      nix-target: web-oci-image
      nix-input-name: gunk-web
      image-name: gunk-web
      source-repo: gunk-dev/gunk-web
      pr-number: ${{ github.event.client_payload.pr_number }}
      action: cleanup
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
