name: Deploy Web Staging

on:
  push:
    branches: [main]
    paths:
      - 'flake.lock'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: gunk-dev/armstrong/.github/workflows/deploy-fly.yml@main
    with:
      app-name: gunk-web-staging
      cue-path: ./apps/web
      environment: staging
      nix-target: web-oci-image
      image-name: gunk-web
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
